console.log(typeof null)
console.log(typeof undefined)
console.log(typeof NaN)
console.log(typeof Infinity)
console.log(typeof -Infinity)
console.log(typeof 1)
console.log(typeof '1')
console.log(typeof true)
console.log(typeof {})
console.log(typeof [])
console.log(typeof function(){})
console.log(typeof Symbol())
console.log(typeof new Date())
console.log(typeof new RegExp())
console.log(typeof new Error())
console.log(typeof string)